@startuml

!include <archimate/Archimate>

skinparam shadowing true
skinparam backgroundColor #EEEBDC
skinparam ArrowColor black
skinparam noteBorderColor black

skinparam rectangle<<behavior>> {
	roundCorner 25
}

sprite $bProcess jar:archimate/business-process
sprite $bActor jar:archimate/business-actor
sprite $bActivity jar:archimate/business-activity
sprite $aService jar:archimate/application-service
sprite $aComponent jar:archimate/application-component

header
Currently under review
endheader

title Business Viewpoint For Lending Flow

rectangle "Customer"  as C <<$bActor>><<behavior>> #Business
rectangle "Relationship Manager"  as RM <<$bActor>><<behavior>> #Business
rectangle "Credit Officer"  as CO <<$bActor>><<behavior>> #Business

rectangle "Complete Documentation"  as CDoc <<$bActivity>><<behavior>> #Business
rectangle "Some kind of handshake\nwith the customer"  as HS <<$bActivity>><<behavior>> #Business

rectangle "2.1 Credit Decision"  as CD <<$bActivity>><<behavior>> #Business
rectangle "3.1 Gather Customer Data"  as GCD <<$bProcess>><<behavior>> #Business
rectangle "3.2 Enablement"  as E <<$bProcess>><<behavior>> #Business
'note left: 1
rectangle "3.3 Draft Documentation"  as DD <<$bProcess>><<behavior>> #Business
rectangle "3.4 Perform Fraud Checks"  as FC <<$bProcess>><<behavior>> #Business
rectangle "3.5 Fulfillment"  as FF <<$bProcess>><<behavior>> #Business

C -d-> RM: Agrees loan shape
RM -[hidden]r- CO
RM -d-> GCD: To cust svcs team
CO -d-> CD
E -u-> CD
GCD -r-> E
E -r-> DD

C -r-> CDoc: signs
DD -u-> CDoc: send to customer

CDoc -d-> FC: signed
FC -r-> FF
CDoc -[hidden]r- HS
DD -[hidden]r- FC

FF -u--> HS : close the deal

rectangle "CRM\n<D365>" as CRM <<$aComponent>> #Application
rectangle "Other Customer\nData SoR" as OCD <<$aComponent>> #Application
rectangle "Credit System" as CS <<$aComponent>> #Application
rectangle "Document Repository" as DS <<$aComponent>> #Application
rectangle "Fraud Checking System" as FCS <<$aComponent>> #Application{
    rectangle "Name List Screening" as NL <<$aService>> #Application
    rectangle "Sanctions Checks" as SANC <<$aService>> #Application
}
rectangle "Position Keeping System" as PK <<$aComponent>> #Application



GCD .d..|> CRM: Opinion
GCD .d.|> OCD: Customer\nData
GCD .d.|> CS: Customer\nCredit Data
E .d.|> CS: Decision
DD .d.|> DS: Store
FC -d-> FCS: check
FF .d.|> PK: create account
FF .d..|> CRM

legend left
Key
====
Business Layer
<$bActor> : Actor
<$bActivity> : Activity
<$bProcess> : Process
----
Technology Layer
<$aService> : Service
<$aComponent> : Component
endlegend

center footer Example business viewpoint

@enduml