@startmindmap
title Thinking about architecture

skinparam shadowing true
skinparam backgroundColor #EEEBDC
skinparam ArrowColor black
skinparam noteBorderColor black

<style>
mindmapDiagram {
    LineColor darkred
}
</style>

*[#lightblue] <b>Pete Potted History</b>
    * <b>UBS</b>
        * Engineer
            * Many years (C++ / Java)
            * XP / Lean / Agile
            * Head of Engineering (Group Ops IT)
            *[#lightgreen] <&star> CTO for Application Delivery
                *_ Group Software\nEngineering Strategy
        * Architect
            * FICC Ops Architect
            * Finance Architect
    * <b>Deutsche</b>
        * Domain Architect
            * Client Technology
            * Regulatory Technology
            * Reference Data CDA
        * F2B Architect
            * CIB MIFID II
            *[#lightgreen] <&star> CIB KYC & Client Perimeter
            * Group BCBS 239
            *[#lightgreen] <&star> Group Party
            *[#lightgreen] <&star> F2B Data alignment
                *_ Risk / finance
        * Distinguished Engineer
            *[#lightgreen] <&star> Engineering\nCareer Development
                *_ Promotions
                *_ Coaching
                *_ Framework
            * Voice of the Engineer
            *[#lightgreen] <&star> Developer Experience
                *_ Virtual Workstations
                *_ Bureaucracy
                *_ Linux Desktop
    * <b>NatWest</b>
        * Principal Engineer
            * Formed PE Role
                *_ Engineering, Architecture,\nData, Hosting
                *_ Tracks with collective\nresponsibility
                *_ Using Lean (VSMs)
                *_ Establishing arch domains
            * Network established\nand leveraged
            * Driving cross group
                *_ Client
                *_ Hosting
                *_ Data
                *_ Payments
                *_ Engineering

*[#lightblue] <b>Why do i think i will</b>\n<b>be good in this role</b>
left side
    * Things will\nfind easy
        * Disrupting the status quo
        * Networking and\nforming partnerships
        * Bringing an engineer mindset
            *_ Digitise / codify
            *_ Reduce bureaucracy
    * Things that will help me
        * Many years as an engineer
        * Many years as an architect
        * Strong knowledge of banking
            *_ IB
            *_ Commercial
            *_ Client centric
        * Building relationships
            *_ Established network
        * Co-designed the architecture process at DB
            *_ Program Arch Gov
            *_ Technical Architecture Governance
            *_ Domain centric decisioning
            *_ Architecture led mindset
            *_ Agile model mindset\narchitecture in agile teams

right side
    * Things that will\nstretch me
        * Influencing across ExCo
            *_ Competing goals
        * Into the detail
            *_ Need detail
            *_ Need to scale
            *_ Finding the balance
        * How to influence\nacross 4000 people
    *[#lightgreen] Things that need\nto change
        * Engineering / Architecture Led
        * Establish group wide architectures
            *_ Too much focus on fireside chats
            *_ Establish challenge into the process
            *_ Focus on front to back designs
        * Establish rigour in the arch process
            *_ Program Architecture
            *_ Strategic assessment
        * Strengthen up the arch principles
            *_ Make them more relevant
        * Specific problems
            *_ Data
            *_ Party / Identity
            *_ Payments
            *_ Core / (Virtual) Accounts

*[#lightblue] Thematically how have you used\nexperiences from other places here at NatWest
    * VSMs
        *_ data driven
        *_ based on facts
    * TDD
        *_ kata oriented
        *_ reusable
    * Coaching DEs
        *_ where did we fail at DB
    * Engineering Communities
        *_ VoE
        *_ Technical decision making
    * Data architecture
        *_ put in one places
        *_ controls design
        *_ real time flows


*[#lightblue] CPC
    * Motivation and Fit
        * Can you describe the type of work environment where you are at your best?
            *_ Unstructured work with no clear outcome
            *_ Prefer some level of pressure to keep the focus
            *_ With some level of technical challenge
        * How does architecture
        *[#lightgreen] What do you know of the role you have applied for
            *_ Director of Architecture
            *_ Operating Model and Practice for discipline of architecture
            *_ Drive and manage architecture
            *_ Set framework, policies and governance
            *_ Champion one bnk mindset
            *_ Develop and govern the target architecture roadmaps
            *_ 4x productive, 10x faster
    * Knowledge and experience
        * What knowledge do you have\nthat will help you succeed?
            *_ Engineering and Architecture experience in spades
            *_ Good working knowledge of how banks work F2B
            *_ Good network already established
        * What knowledge and skills will you bring to job
            *_ Engineer
            *_ Architect
            *_ Co-designed the architecture process at DB\n(program, technical and enterprise architecture)
        * How do you consider risk as part of your work?
            *_ Operational risk
            *_ Delivery Risk
        *[#lightgreen] What will you find most challenging
            *_ Scale of the role
            *_ I am an engineer at heart, I want to be in the code
            *_ Forming agreements across the bank limiting\nthe effect of compromises
            *_ I have already moved away from architect to\nmanager of architects
            *_ Politics, this is no longer whats the correct thing\nto do.  ExCo motivations are different.
    * Connected
        * When put in initiative or intervention\nthat helped develop a team-working\nculture across business area
            *_ <b>Black Leadership Forum</b> became champion for the lanhuage of engineering
            *_ TDD Katas
            *_ saw issues in the EE program and created more
            *_ XP_Dojo
        * What have you done to break down siloed working?
            *_ <b>Round table</b> agreed with Jenny that we need a round table discussion to solve for things like KYC, Payments etc
            *_ <b>Virtual Accounts design</b>
            *_ Moving away from siloed architecture more generally
            *_ Forming partnerships across domains, pulling right\npeople into meets to openly show and tell\nSteve Haynes mortgages and loans
    * Trusted Advisor
        * When built strategic partnership\nwith colleague
            *_ <b>NatWest first 90 days</b> was all about network (Declan, Ted, Iain, SteveH, Ian and Robert, Jenny)
            *_ <b>RDA stakeholders</b>: formed partnership with Retail and Finance Mngt teams
            *_ Now focusing on business side -> Sapna's team
        * When encouraged others to use industry\nand job-relevant knowledge to better\nmeet customer demands
            *_ <b>VSMs from Lean</b> enable you to measure cost of the process.  Needs care.
            *_ <b>Archimate at DB</b>, moved the architecture book. Learned\nfrom KYC with regulators that its very usable for\nstructured conversations with partners and regulators
            *_ Markdown in Nathan and Elissa
            *_ Data Products experience and controls
    * Critical Thinker
        * How have you used data to make a decision
            *_ Plan Do Check Act
            *_ <b>Google discussions</B> ... pushing them for a year on year\nview with cost projections for LDC Exit
            *_ <b>Developer Desktop</b> defined a set of developer acceptance\ncriteria based on compilation of common repo
            *_ <b>JetBrains License Server</b>: created a 500k save from nothing (few meets)
            *_ <b>VSMs at UBS</b> ... now reusing the same technique where ...
            *_ Hosting .. waltz ... aptio, cmdb,
            *_ principal led decision making is key
            *_ Simplification agenda ... how many decoms and how\nmuch save does it bank use
        * When have you made a decision that has had\npositive impact on a customer or colleague?
            *_ <b>RDA Real Time</b>: hypothesis was that lack of real time impacts RWA\nData actually showed minimal impact to RDA from retail\nable to get them to focus on Unity and do real time later
            *_ <b>JetBrains License Server</b>: ran it myself as side of desk, migrated over a two month period.  Negotiated with JB myself.
    * Change Ready
        * Self directed learning
        * Coaching
        * Learns from experience
    * Improver Innovator
        * Innovation that was shared with\nother teams as best practice
            *_ <b>Director Promotions</b>: focused on engineers using a data driven approach (Drefus Model).  Copied into career development frameworks.
            *_ <b>Next Gen</b>: prototyped with open source learning platform, later incorporated into
            *_ Application assessment, into Waltz
            *_ archimate as a simple way to draft an architecture
        * When have you encouraged innovation in your team
            *_ DTR process Digitising it
            *_ digitising the architecture ... using PUML snd C4
            *_ disrupting the engineering council ... languages ... tech radar

@endmindmap