@startmindmap
title Core Competency Assessment

skinparam shadowing true
skinparam backgroundColor #EEEBDC
skinparam ArrowColor black
skinparam noteBorderColor black

<style>
mindmapDiagram {
    LineColor darkred
}
</style>

*[#lightgreen] Star
    * h

* CPC Assessment


@endmindmap